### ISSUE TITLE
npm test and npm start fails

### ISSUE THREAD

**Issue by wingmanzz** [jaystack/odata-v4-server-pgsql-example#3]
on fresh install of node v8.11.3:

  OData V4 example server
    Products
      1) "before each" hook for "should get all products (GET /Products)"

  0 passing (29ms)
  1 failing

  1) OData V4 example server "before each" hook for "should get all products (GE
T /Products)":
     TypeError: Cannot read property 'highWaterMark' of undefined
      at ODataServer.get (_stream_duplex.js:73:32)
      at propNames.forEach (node_modules\odata-v4-server\build\lib\metadata.js:2
95:49)
      at Array.forEach (<anonymous>)
      at Object.createMetadataJSON (node_modules\odata-v4-server\build\lib\metad
ata.js:294:15)
      at Function.$metadata (node_modules\odata-v4-server\build\lib\server.js:18
7:137)
      at new ODataProcessor (node_modules\odata-v4-server\build\lib\processor.js
:416:81)
      at Function.createProcessor (node_modules\odata-v4-server\build\lib\server
.js:176:16)
      at Function.execute (node_modules\odata-v4-server\build\lib\server.js:145:
30)
      at Context.beforeEach (test\pgsql.spec.js:34:32)

[mochawesome] Report saved to report\odata-v4-server.html

npm ERR! Test failed.  See above for more details.

npm start also fails with same error.

**Comment by santiagohgarcia** [comment]
Installing node v8.9.0 solves the issue for me

**Comment by manandharsabir** [comment]
I am getting same error for node: '8.11.2'... can anyone help ?
